# Workflow to validate commits to an open PR.

name: Validate PR

env:
  INSTALL_EDM_VERSION: 3.2.3
  PYTHON_VERSION: 3.6

on:
  pull_request

jobs:
  test-with-edm:
    runs-on: ubuntu-latest

    steps:
      - name: Install necessary Linux packages
        run: |
          sudo apt-get update
          sudo apt-get install graphviz libgraphviz-dev pkg-config
          sudo apt-get install qt5-default
          sudo apt-get install libxkbcommon-x11-0
          sudo apt-get install libxcb-icccm4
          sudo apt-get install libxcb-image0
          sudo apt-get install libxcb-keysyms1
          sudo apt-get install libxcb-randr0
          sudo apt-get install libxcb-render-util0
          sudo apt-get install libxcb-xinerama0
        if: runner.os == 'Linux'
      - name: Check out the PR branch
        uses: actions/checkout@v2
      - name: Cache EDM packages
        uses: actions/cache@v2
        with:
          path: ~/.cache
          key: ${{ runner.os }}-${{ hashFiles('ci/edmtool.py') }}
      - name: Set up EDM
        uses: enthought/setup-edm-action@v1
        with:
          edm-version: ${{ env.INSTALL_EDM_VERSION }}
      - name: Provision bootstrap environment
        run: |
          edm install -y --version=${{ env.PYTHON_VERSION }} click
      - name: Create test environment
        run: |
          edm run -- python ci/edmtool.py install --toolkit='pyqt5'
      - name: Run tests
        run: |
          edm run -- python ci/edmtool.py test --toolkit='pyqt5'
