# Workflow to run tests weekly on the main branch, against latest ETS sources.

name: Weekly check

env:
  INSTALL_EDM_VERSION: 3.2.3
  PYTHON_VERSION: 3.6
  PYTHONUNBUFFERED: 1
  QT_DEBUG_PLUGINS: 1

on:
  workflow_dispatch:
  schedule:
    # Run at 01:48 UTC every Friday
    - cron: '48 1 * * 5'

jobs:
  test-with-edm:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        toolkit: ['pyqt', 'pyqt5', 'pyside2']

    steps:
      - name: Install necessary Linux packages
        run: |
          sudo apt-get update
          sudo apt-get install graphviz libgraphviz-dev
          sudo apt-get install libxkbcommon-x11-0
          # Needed for the Enable install
          sudo apt-get install libglu1-mesa-dev
      - name: Check out the PR branch
        uses: actions/checkout@v2
      - name: Cache EDM packages
        uses: actions/cache@v2
        with:
          path: ~/.cache
          key: ${{ runner.os }}-${{ hashFiles('ci/edmtool.py') }}
      - name: Set up EDM
        uses: enthought/setup-edm-action@v1
        with:
          edm-version: ${{ env.INSTALL_EDM_VERSION }}
      - name: Provision bootstrap environment
        run: |
          edm install -y --version=${{ env.PYTHON_VERSION }} click
      - name: Create test environment
        run: |
          edm run -- python ci/edmtool.py install --toolkit=${{ matrix.toolkit }} --source
      - name: Run test suite
        uses: GabrielBB/xvfb-action@v1
        with:
          run: edm run -- python ci/edmtool.py test --toolkit=${{ matrix.toolkit }}

  notify-on-failure:
    needs: [test-with-edm]
    if: failure()
    runs-on: ubuntu-latest
    steps:
      - name: Notify Slack channel on failure
        uses: voxmedia/github-action-slack-notify-build@v1
        with:
          channel_id: ${{ secrets.ETS_BOTS_SLACK_CHANNEL_ID }}
          status: FAILED
          color: danger
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_ACTION_SECRET }}

  notify-on-success:
    needs: [test-with-edm]
    if: success()
    runs-on: ubuntu-latest
    steps:
      - name: Notify Slack channel on success
        uses: voxmedia/github-action-slack-notify-build@v1
        with:
          channel_id: ${{ secrets.ETS_BOTS_SLACK_CHANNEL_ID }}
          status: SUCCESS
          color: good
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_ACTION_SECRET }}
